apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: To be assigned to user to allow installation of Keycloak CRs.
  creationTimestamp: "2021-02-10T18:19:57Z"
  name: keycloak-project-admin
rules:
- apiGroups:
  - keycloak.org
  resources:
    - keycloaks
    - keycloaks/status
    - keycloaks/finalizers
    - keycloakrealms
    - keycloakrealms/status
    - keycloakrealms/finalizers
    - keycloakclients
    - keycloakclients/status
    - keycloakclients/finalizers
    - keycloakbackups
    - keycloakbackups/status
    - keycloakbackups/finalizers
    - keycloakusers
    - keycloakusers/status
    - keycloakusers/finalizers
  verbs:
  - get
  - create
  - update
  - patch
  - delete
  - list
