apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: keycloak-template
metadata:
  annotations:
    description: deployment for ${KEYCLOAK_NAME}
  name: ${KEYCLOAK_NAME}
objects:
- apiVersion: keycloak.org/v1alpha1
  kind: Keycloak
  metadata:
    labels:
      app: ${KEYCLOAK_NAME}
    name: ${KEYCLOAK_NAME}
    namespace: ${KEYCLOAK_NAMESPACE}
  spec:
    DisableDefaultServiceMonitor: true
    externalAccess:
      enabled: true
    instances: 1
    keycloakDeploymentSpec:
      experimental:
        env:
          - name: JAVA_TOOL_OPTIONS
            value: '-Dcom.redhat.fips=false'   