
# Keycloak instance
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ${RH_SSO_NAME}-template
metadata:
  annotations:
    description: Template for ${RH_SSO_NAME}
  name: ${RH_SSO_NAME}-template
objects:
  - apiVersion: keycloak.org/v1alpha1
    kind: Keycloak
    metadata:
      name: ${RH_SSO_NAME}
      labels:
        app: ${RH_SSO_NAME}
    spec:
      externalAccess:
        enabled: true
      instances: 1
      keycloakDeploymentSpec:
        experimental:
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Dcom.redhat.fips=false'    
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "300m"
            memory: "1Gi"
      postgresDeploymentSpec:
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "600m"
            memory: "1Gi"
parameters:
  - name: RH_SSO_NAME
    value: keycloak
